### ISSUE TITLE
Left Trackball

### ISSUE THREAD

**Issue by wolfiex** [Schievel1/dactyl_manuform_r_track#12]
Other than mirroring the guide, and configuring the keymap accordingly, am I likely to encounter any problems if trying to have the trackball on the Left?

**Comment by Schievel1** [comment]
Yes, but only things that can be easily fixed by software. 
- since this is using Arduinos, we do not have any more resources to send the trackball data over via the serial bitbanging cable between the two halves. Therefore you need to make the left side the master and plug the USB cable into the left side. Adjust (or delete since left is the default) this line accordingly https://github.com/qmk/qmk_firmware/blob/d6ce42ae5b1093eeae215c073c733c800195ec28/keyboards/handwired/tractyl_manuform/5x6_right/arduinomicro/config.h#L32
- you need to change not only the keymap but also the layout itself https://github.com/qmk/qmk_firmware/blob/d6ce42ae5b1093eeae215c073c733c800195ec28/keyboards/handwired/tractyl_manuform/5x6_right/5x6_right.h#L38
- with the trackball an the left you need to put the Arduino Micro into the left half and the Pro Micro into the right. You need to adjust the pins accordingly https://github.com/qmk/qmk_firmware/blob/d6ce42ae5b1093eeae215c073c733c800195ec28/keyboards/handwired/tractyl_manuform/5x6_right/arduinomicro/config.h#L23
- I guess the trackball sensor rotation/ inversion will need some adjustment as well https://github.com/qmk/qmk_firmware/blob/d6ce42ae5b1093eeae215c073c733c800195ec28/keyboards/handwired/tractyl_manuform/5x6_right/config.h#L24

That's all that comes to my mind right now.
